### ISSUE TITLE
Memento upload image scaled to fit in upload box

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#13]
When uploading a memento, some images won't scale into the box properly, only occurs on non-squared images. Image include for example (from beta tester). 

![memupload](https://cloud.githubusercontent.com/assets/17418822/14114178/52a585ee-f593-11e5-8195-dac8b3e09822.jpg)

**Comment by NHungate** [comment]
Modified uploader to prevent cropping and to keep the proportions of the original image
