### ISSUE TITLE
Fix memento thumbnail preview on Organizations listing page

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#19]
Currently the thumbnail view of mementos on the organizations listing page shows a slightly reduced image size but is a small clip of the whole memento image.

**Comment by vinneyk** [comment]
Remove memento images from org search results view. Display short description instead; wrap, do not hide on smaller screen (?)

**Comment by vinneyk** [comment]
Closed as duplicate. Further discussion of a re-design of the organization summary can take place when the time is right.
