### ISSUE TITLE
Returning authenticated users don't get freshly generated feed.

### ISSUE THREAD

**Issue by vinneyk** [Pixanthropy/pixanthropy-web#2]
Users who sign in with the "Remember me" option checked will not be asked to log in until their login cookie is expired or deleted. We need to ensure that these users have a fresh feed when they arrive.

**Comment by vinneyk** [comment]
Disable remember me feature on UI

**Comment by konisland** [comment]
Believe this issue can be closed, now that no longer generate different feed each time. Will verify that there are no issues generating feed and close issue.
