### ISSUE TITLE
Modify Menu Layout

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#28]
Under the hamburger menu icon, have the menu pull up as it currently does with new layout:
-Balance (with green $# as now)
-Add Funds (using existing green button as is now)
Line Break
-Donation History
-Settings
Line Break
-Log Off

Under the 'Settings' option will still link to the existing 'manage account' page where you can change password, change image icon, etc.

**Comment by vinneyk** [comment]
Resolved by d239a2a34a1c
