### ISSUE TITLE
Resize Nav Bar 'Pix Logo' to be slightly smaller

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#32]
Increase the size of the main header by 10 to 15%. 
Would like the items on header to remain same size (i.e., logo and font sizes) Main purpose is to add a little bit of black above and below the 'pix logo' to clean up the look. The buttons (sign-up/log-in) can scale with the header size

**Comment by vinneyk** [comment]
Completed in commit 87328e4244c9
