### ISSUE TITLE
Modify the purchasing controls UI to show all steps in breadcrumb navigation.

### ISSUE THREAD

**Issue by vinneyk** [Pixanthropy/pixanthropy-web#35]
All nav items should be displayed but only allow backwards navigation.

**Comment by NHungate** [comment]
I'm not quite sure what you mean? Purchase UIs have breadcrumb navigation currently, with links that allow users to visit previous stages of the purchasing process.

**Comment by vinneyk** [comment]
@NHungate We want to show all steps from the beginning so that users can see what steps they'll need to complete. Currently, we only show a breadcrumb trail of where you've been. We want a roadmap of where you're heading.
