### ISSUE TITLE
Minor Text Corrections 

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#36]
- [x] Replace "Recent Contributors" with "Donors" on Memento Details View
  Search for "Recent Contributors" or "Contributor(s)" and replace with "Donors" 
  Case invariant, Plural or Singular invariant
  All Cases become Donors
  Gist: want people who have donated to a memento to always be referred to as Donors any where we are recognizing them. 
- [x] Replace "Purchase Credits" with "Add Funds" on payment control screen 
- [x] Left-Align (Flush left, ragged right) text on organizations page (all orgs). Currently organization description is centered; prefer text be aligned left but not justified.

**Comment by NHungate** [comment]
Replaced all text items and fixed alignment
