### ISSUE TITLE
Checkout is not updating the payment source for accounts with existing credit card.

### ISSUE THREAD

**Issue by vinneyk** [Pixanthropy/pixanthropy-web#39]
When checking out, enter a new credit card. The new card is changed in Stripe but,
1. The new card is not set as the default payment option
2. The purchase is using the previous payment source id
3. `ProcessorSourceId` and `ProcessorSourceDescription` fields of the Users table are not changed

**Comment by RHIssa** [comment]
Will need to reproduce in more detail, my tests show it should be working as expected.
I've modified the purchase provider to explicitly set the new card as the default payment option - but it shouldn't have been possible to charge the old card at all as that card should've gotten deleted altogether.
If the `ProcessorSourceId` field is not getting updated then I'm tempted to say that something must've failed without returning an error, but I am unable to reproduce such events.

**Comment by vinneyk** [comment]
@rissaman your update did the trick!
