### ISSUE TITLE
Login Controls - Password Requirement

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#43]
Change the password requirements on 'sign-up' to 2 requirements: 1) min char length (6) 2) one numeric or special character. Then insert text below permanently (replacing existing that only shows up when don't meet requirements)

Insert Text: Passwords must be 6 characters or longer and contain at least one number or symbol (like !@#$%^)
- Same-- font/weight/etc. as text under email _'This will be used for your login but will not be shared'_
- Place -- under Password box (as is text under email box -  thus above confirm box)

Addt: Comments - the "RED" text explaining which PW requirement wasn't met can still work as does, but still want permanent text requirements placed below PW Box. 
One Question: is Password case-sensitive? (if so, maybe should add that line onto 'insert text' above.

**Comment by vinneyk** [comment]
Completed on aa06f3be0769
