### ISSUE TITLE
Pixanthropy Fee

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#46]
Currently have "Pix Fee" set to zero as of Friday Sep 9 -

Q: should leave payment accounts the same (i.e., pix fee as platform fee and leaving that structure in place?) 

Option 1: can we leave 'pix platform fee' structure in place, but allow it to be an option users choose to add funds to?

**Comment by vinneyk** [comment]
Commit #478ba9662ae3 removes pass through Stripe account and platform fee.
#afc6387eaf13 removes the pix fee from the payment calculation.
