### ISSUE TITLE
Expand the donation button to encompass badges on memento badge ui

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#55]
Currently when looking at a memento - the green heart on the bottom right will prompt 'donation box', expand the 'button effect' across horizontally the entire memento badge ui. 
![screen shot 2016-10-07 at 11 00 31 am](https://cloud.githubusercontent.com/assets/17418822/19198728/e4f220de-8c7d-11e6-9f85-156f59e6d8b6.jpg)

**Comment by vinneyk** [comment]
Completed in `0c1d56c95645`
