### ISSUE TITLE
Error - adding funds to existing balance not allowing confirm option.

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#64]
Donation to Existing Memento with funds balance existing and new funds being added to make the donation more (i.e., $50 donation, where $25 is on account and trying to add $25 more in the same donation box window) doesn't allow the final 'confirm' box to be clicked. 

Pulled up with existing CC details in place (wouldn't allow confirm) also clicked CC details and re-entered the CC information clicked next and still (wouldn't allow confirm) 

<img width="1280" alt="screen shot 2017-01-06 at 6 03 36 pm" src="https://cloud.githubusercontent.com/assets/17418822/21776379/5f8f375a-d657-11e6-8b9c-1e6938bb439a.png">

**Comment by NHungate** [comment]
Fixed. Confirm button was stuck in a disabled state due to expecting an email even on authenticated users.
