### ISSUE TITLE
Internal Service Error - Cannot add memento and funds simultaneously (causes error)

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#65]
Have discovered reoccurring issue for new users. If they have an account balance of $0 and go to 'add memento' they can place the image in the box and select the amount to donate, click next to enter in their credit card details, then when the click confirm they get 2 red internal service errors.
Have had this same issue with 5 users now. In each case we had them open a second tab and go to the 'add credits' screen and add the funds to their account (works fine) and then go and process the 'add memento' (works fine). So error only occurs when they try to add memento and funds. 
![50640352150__9b309058-1e53-49b1-9a40-c6d581e2eb33 jpg](https://cloud.githubusercontent.com/assets/17418822/22050354/70d8fdec-dcf7-11e6-9d9b-c78a1b305323.jpeg)

**Comment by vinneyk** [comment]
Corrected in branch `fix/payment-concepts` and released in version `001.003.000`.
