### ISSUE TITLE
Unable to Scroll on Mobile when clicking green donate tab

### ISSUE THREAD

**Issue by konisland** [Pixanthropy/pixanthropy-web#67]
Error exists on both IOS and Android phones. When clicking on a memento image, pulls up the memento details view (scrolling works fine here) but if you click on the green donate button ($1$5etc) on the top of the view, it takes you to the first page of the donation window (select amount) you cannot move off this screen because you cannot scroll down to 'continue' button. 

Image obvi can't show that can't scroll - but can see where the bottom button is below the view and there is no way to get to it.  Additionally, noticed that the 'feedback' tab also doesn't scroll in mobile view, so can't click into the box to enter feedback, can only read the writing. 
![img_9472](https://cloud.githubusercontent.com/assets/17418822/22050543/016021dc-dcf9-11e6-8d2c-af5d193e27f8.PNG)

**Comment by vinneyk** [comment]
@konisland, this is likely due to your low battery. lol 😆
